tasks:
  - init: >
      touch database/database.sqlite &&
      cp .env.gitpod .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      npm i &&
      php artisan key:generate &&
      php artisan migrate --seed
    command: >
      php -S 0.0.0.0:8000 -t public
